baseURL = "https://nazagara.github.io/"
title = 'Nazareno Garagiola'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

# Default config
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Footer
showFooter = true

[params.social]
linkedin = "https://linkedin.com/in/nazareno-garagiola"
github = "https://github.com/nazagara"
email = "garagiola@depend.uni-saarland.de"
